# SPDX-License-Identifier: CC0-1.0
---
dontChroot: true
timeout: 300
verbose: true

script:
  - command: "/usr/local/libexec/kaskados-configure-gpu ${ROOT}"
    timeout: 300

i18n:
  name: "Configuring graphics driver"
  name[ru]: "Настройка графического драйвера"
