# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 180
verbose: true

script:
  - command: "/usr/bin/pacman-key --init"
    timeout: 120
  - command: "/usr/bin/pacman-key --populate archlinux kaskados"
    timeout: 120

i18n:
  name: "Preparing package verification"
  name[ru]: "Подготовка проверки пакетов"
